apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-state
spec:
  serviceName: sql-service
  replicas: 3
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql
        image: mysql
        ports:
        - containerPort: 3306
          name: web
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: "12345678"
         - name: MYSQL_ROOT
           value: "root"
         - name: MYSQL_HOST
           value: "mysql"
         - name: MYSQL_DATABASE
           value: "classicmodels"
        volumeMounts:
        - name: www
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi